apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cluster.open-cluster-management.io/v1beta1","kind":"Placement","metadata":{"annotations":{},"name":"dev-placement","namespace":"openshift-gitops"},"spec":{"predicates":[{"requiredClusterSelector":{"labelSelector":{"matchExpressions":[{"key":"cluster_env","operator":"In","values":["dev"]}]}}}]}}
  creationTimestamp: "2023-04-12T11:58:24Z"
  generation: 1
  name: dev-placement
  namespace: openshift-gitops
  resourceVersion: "513275"
  uid: 8374e1e9-997c-4296-8529-3feb457daea9
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: cluster_env
          operator: In
          values:
          - dev
status:
  conditions:
  - lastTransitionTime: "2023-04-12T11:58:24Z"
    message: Placement configurations check pass
    reason: Succeedconfigured
    status: "False"
    type: PlacementMisconfigured
  - lastTransitionTime: "2023-04-12T11:58:24Z"
    message: All cluster decisions scheduled
    reason: AllDecisionsScheduled
    status: "True"
    type: PlacementSatisfied
  numberOfSelectedClusters: 1
