apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook1
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/achieris/product-demo-gitops.git
    targetRevision: main
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook1 
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
