apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: openshift-gitops
spec:
  project: default
  sources:
  - repoURL: https://achieris.github.io/product-demo-gitops 
    targetRevision: "0.1.0" 
    chart: nginx-chart
    helm:
      valueFiles:
      - $values/values-dev.yaml
  - repoURL: 'https://github.com/achieris/product-demo-gitops.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx 
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
